In [21]:
from numpy import dtype
import numpy as np
    print(np.__version__)
    
    arr = np.array((1, 2, 3, 4, 5))
    print(arr)
    type(arr)
    arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr_2D)
    
    lst = [10, 20, 30, 40, 50,]
    arr = np.array(lst, dtype=int)
    print(arr)
    print(arr.dtype)
    
    arr = np.array(lst, dtype=complex)
    
    arr = np.array(lst, dtype=np.int8)
    print(arr)
    print(arr.dtype)
    
    arr = np.array(lst, dtype="int8")
    print(arr)
    print(arr.dtype)
    
    
    
    

2.1.3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[10 20 30 40 50]
int64
[10 20 30 40 50]
int8
[10 20 30 40 50]
int8


In [11]:
names = np.array(['Ala', 'Ola', 'Ula'])
print(names.dtype)
# little endian, Unicode, 3znaki

<U3


In [15]:
dates = np.array(['2024-12-02', '2024-12-06'], dtype='M') # muszą być formacje iso yyyy-mm-dd
print(dates.dtype)

datetime64[D]


### Konwersja typów

In [16]:
int_arr = np.array([1, 2, 3, 4, 5])

# create new array
str_arr = np.array(int_arr, dtype="U")
print(str_arr)

['1' '2' '3' '4' '5']


In [17]:
float_arr = np.float32(int_arr)
print(float_arr)

[1. 2. 3. 4. 5.]


In [19]:
complex_arr = int_arr.astype(complex)
print(complex_arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# create empty array

In [23]:
empty_array = np.empty([3, 2], dtype=int)
print(empty_array)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
zerox_array = np.zeros([2, 2])
print(zerox_array)

[[0. 0.]
 [0. 0.]]


In [25]:
ones_array = np.ones(5, dtype=int)
print(ones_array)

[1 1 1 1 1]


In [27]:
full_arr = np.full([3, 3], 42, dtype=int)
print(full_arr)

[[42 42 42]
 [42 42 42]
 [42 42 42]]


In [28]:
item = 

lst = [1, 2 ,3, 4, 5]
arr = np.asarray(lst)
print(arr)

[1 2 3 4 5]


In [30]:
lst = [1, 2 ,3, 4]

iter_ob = iter(lst)

arr_iter = np.fromiter(iter_ob, dtype=np.float32) # fromiter będzie działać z każdym generatorem. poza tym jeden obiekt może mieć rózne iteratory.
print(arr_iter)

[1. 2. 3. 4.]


In [37]:
buffer_lst = b'ala ma kota i wszy'

arr_buffer = np.frombuffer(buffer_lst, count=-1, offset=0, dtype='S1')
print(arr_buffer)

[b'a' b'l' b'a' b' ' b'm' b'a' b' ' b'k' b'o' b't' b'a' b' ' b'i' b' '
 b'w' b's' b'z' b'y']


In [40]:
np.arange(start=0, stop=10, step=.5, dtype=np.float32)
print(arr)

[1 2 3 4 5]


In [41]:
np.linspace(start=0, stop=100, num=5, dtype=int) # podajemu ile punktów chcemy mieć

array([  0,  25,  50,  75, 100])

In [42]:
np.logspace(start=0, stop=10, num=5, base=2, dtype=int) # base to podstawa logarytmu, wylicza logarytm z podstawą base

array([   1,    5,   32,  181, 1024])